# Generated by Django 3.2.12 on 2022-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20220318_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='votants',
            name='idees',
            field=models.ManyToManyField(through='vote.Voter', to='vote.Idees'),
        ),
    ]
